### ISSUE TITLE
When I try to convert my keyboard inputs to analog it doesn't work

### ISSUE THREAD

**Issue by JackinSac** [vlad-ulmeanu01/trackmania-ml-tas#3]
I followed all the steps but when I tried to convert my keyboard inputs to analog it says this:

Reading hyperparams from B.txt!
tm_data_reader, convert_press_to_steer.py, preprocess_hyperparams:
CUTOFF_TIME = 22000
Traceback (most recent call last):
  File "C:\Users\jacka\Desktop\trackmania-ml-tas-needs-testing\tm_data_reader\convert_press_to_steer.py", line 100, in <module>
    main()
  File "C:\Users\jacka\Desktop\trackmania-ml-tas-needs-testing\tm_data_reader\convert_press_to_steer.py", line 95, in main
    process_inputs(fin, sys.argv[1])
  File "C:\Users\jacka\Desktop\trackmania-ml-tas-needs-testing\tm_data_reader\convert_press_to_steer.py", line 70, in process_inputs
    l, r = map(int, s[0].split('-'))
ValueError: not enough values to unpack (expected 2, got 1)

**Comment by vlad-ulmeanu01** [comment]
Hi! Thanks for trying the code out)))

I think that the `convert_press_to_steer.py` code expects the keyboard input script to be in the following format for left/right turns for example:
`1230-2340 press left`
hence the expected dash between the times.
The `ValueError: not enough values to unpack (expected 2, got 1)` makes me think the keyboard input had something weird like `1230 press left`, because there isn't any `neutral shift` command to call at `2340`.


I think that if I could get the keyboard input script we could figure this out. If you want, call me on discord at `catalyst#1429`.

Thanks again for trying this out!

**Comment by JackinSac** [comment]
i figured it out, i had some analog inputs mixed in with my keyboard inputs from bruteforcing the normal way earlier, once i removed the analog it worked, thanks

**Comment by vlad-ulmeanu01** [comment]
Oh great, let me know if you have another problem or if you found an improvement
Btw sorry, I didn't think that somebody would come up with a combination of steer and press for the converter, it was only meant to run on something that came out straight from the `generate_input_file.py`))
